name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image from Dockerfile
        run: docker build -t sunandandas/docker-react .

      - name: Run tests in container
        run: docker run -e CI=true sunandandas/docker-react npm test